name: Bump Package Version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Select the version bump type'
        required: true
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Github
      - run: |
        git config --global user.email "william-andy@sensyn-robotics.com"
        git config --global user.name "andy william"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Bump Version
        run: |
          if [ "${{ github.event.inputs.bump-type }}" == 'patch' ]; then
            npm version minor
          elif [ "${{ github.event.inputs.bump-type }}" == 'minor' ]; then
            npm version minor
          elif [ "${{ github.event.inputs.bump-type }}" == 'major' ]; 
            npm version major
          fi

      - name: Push changes to repository
        run: |
          git push --follow-tags