name: Bump Package Version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Select the version bump type'
        required: true
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          version-type:  ${{ github.event.inputs.bump-type }}
          skip-tag:  'true'
      - name: Push changes to repository
        run: |
          cat package.json